### ISSUE TITLE
Should We Explicitly Identify Our Cityspire Cities/Locations?

### ISSUE THREAD

**Issue by danoand** [Lambda-School-Labs/cityspire-d-ds#1]
**BACKGROUND**

My intuition is that we should explicitly identify the cities/locations we support in the Cityspire app.  

If we go down this route, then the logical implications are:

- Users would need to search (e.g. typeahead, select from a list, traditional search) for the cities that are supported
- If the user wants a city that is not supported they are SOL :)
- The the DS related data (db, model, scores/predictions) would be limited to this supported list

My proposal is to limit the app to the top 50 US cities by population, which are: 

1  New York City
2  Los Angeles
3  Chicago
4  Houston
5  Phoenix
6  Philadelphia
7  San Antonio
8  San Diego
9  Dallas
10  San Jose
11  Austin
12  Jacksonville
13  Fort Worth
14  Columbus
15  Charlotte
16  San Francisco
17  Indianapolis
18  Seattle
19  Denver
20  Washington
21  Boston
22  El Paso
23  Nashville
24  Detroit
25  Oklahoma City
26  Portland
27  Las Vegas
28  Memphis
29  Louisville
30  Baltimore
31  Milwaukee
32  Albuquerque
33  Tucson
34  Fresno
35  Mesa
36  Sacramento
37  Atlanta
38  Kansas City
39  Colorado Springs
40  Omaha
41  Raleigh
42  Miami
43  Long Beach
44  Virginia Beach
45  Oakland
46  Minneapolis
47  Tulsa
48  Tampa
49  Arlington
50  New Orleans

**QUESTIONS/NEXT STEPS**

- Does this make sense to you all? If so, is this a reasonable list to at least begin?
- We'll need to confirm our assumptions with the rest of the team

**Comment by AaronReichert** [comment]
I think we should gather all the data we can then create a key table of the cities using an inner join and use that as the list of cities.
Just a possible option.

**Comment by danoand** [comment]
Yea... definitely makes sense to have what data we can find drive the list of cities.  I think the web guys will need that list in their database or quickly fetched from the DS API so the search experience for the user is snappy.

If we return that list as the result of joining multiple tables/sources on the DS end, that query may seem sluggish.  Food for thought as we dig into it

**Comment by danoand** [comment]
Looking into data first.  Maybe focus on the top 50 cities for MVP

**Comment by danoand** [comment]
In the short term... closed on the top 100 cities by population.  Can pull the city data using the `GET .../cities` route

See the wiki for documentation on the high priority routes: https://github.com/Lambda-School-Labs/cityspire-d-ds/wiki/Sample-Routes

Closing this issue
