### ISSUE TITLE
Close on Data Elements (Scores, Predictions, etc.) Returned via DS API Requests

### ISSUE THREAD

**Issue by danoand** [Lambda-School-Labs/cityspire-d-ds#2]
### Background
This issue/task is to close on the chunks of data (scores, predictions, etc.) that the DS API will return to callers (ie. Web Backend).

Looking at the iOS Whimsical and our past conversations, I see these data chunks.

Listing those with sample route paths

### On the iOS Mockups [HIGH PRIORITY]
- List of supported cities (stored in the DS database)
  - route: `GET /cities`
- Average Rent (metric) [**_Palmer_** (Zillow)] (need)
  - route: `GET /rent_avg/<city>` 
- Rent given parameters (prediction) [**_Palmer_** (Zillow)] (need)
  - route: `GET /rent_srch/<city>`
- Walkability Score (metric) (need) [**Dan**]
  - route: `GET /walk_scr/<city>`
- Crime Score (metric) [**_Dan_**] (need)
  - route: `GET /crime_scr/<city>` (return a score of 1-5)
- Air Quality Score (metric) [Medium - **_Palmer_**] (need)
  - route: `GET /air_qual_scr/<city>`

### Other Data Chunks We've Talked About
- Overall Livability Score (metric) [High (simple calculation across multiple dimensions)] (need)
  - route: `GET /city_scr/<city>` (return a high-level score and then underlying sub-scores)
- Cost of Living Score (metric) [High - **_Dan_**]
  - route: `GET /col_scr`
- School Scores - individual schools in the user's location (data) [High - **_Aaron_**]
  - route: `GET /schools`
- Overall School Score - district? (metric) [High - **_Aaron_**]
  - route: `GET /schools_scr`
- Covid Score (metric) - a score that depicts changes in Covid cases (e.g. `green`, `yellow`, `red`; or `0`, `1`, `2`) [High - **_Dan_**]
  - route: `GET /covid_scr`
- Culture/Dining/Entertainment Score  (metric) [Low]
  - route: `GET /culture_scr`

**Comment by danoand** [comment]
One of the other teams found some walkability/transit data in a csv somewhere...

**Comment by danoand** [comment]
### FBI Crime Data

- [FBI crime by city.csv.zip](https://github.com/Lambda-School-Labs/cityspire-d-ds/files/5846818/FBI.crime.by.city.csv.zip): Aaron found this one
- [Table_8_Offenses_Known_to_Law_Enforcement_by_State_by_City_2019.xls.zip](https://github.com/Lambda-School-Labs/cityspire-d-ds/files/5871065/Table_8_Offenses_Known_to_Law_Enforcement_by_State_by_City_2019.xls.zip): looks like   this is more recent and has more cities
- [CrimeRatesByCity_ReadyForDBImport.csv.zip](https://github.com/Lambda-School-Labs/cityspire-d-ds/files/5876449/CrimeRatesByCity_ReadyForDBImport.csv.zip): crime data to be imported in a DS backend database

### US City Database (https://simplemaps.com)

- [uscities.xlsx](https://github.com/Lambda-School-Labs/cityspire-d-ds/files/5871011/uscities.xlsx)
- Includes lat/long geocode locations for each city which may be needed to get a Walk Score from https://walkscore.com

**Comment by danoand** [comment]
Closed on these as high priority items in our call tonight with the web dev guys (Thur Jan 21)

- Average Rent (metric) [High - **_Palmer_** (Zillow)] (need)
  - route: `GET /rent_avg/<city>` 
  - return 1-5 score
  - return dollar amount
- Rent given parameters (prediction) [High - **_Palmer_** (Zillow)] (need)
  - route: `GET /rent_srch/<city>`
  - return 1-5 score
  - return dollar amount
- Walkability Score (metric) [Low] (need)
  - return 1-5 score
  - route: `GET /walk_scr/<city>`
- Crime Score (metric) [High - **_Aaron_**] (need)
  - route: `GET /crime_scr/<city>` 
  - return a score of 1-5
  - return other data (see Aaron's comment below)
  - return 
- Air Quality Score (metric) [High - **_Dan_**] (need)
  - return a score of 1-5
  - route: `GET /air_qual_scr/<city>`

### Other Data Chunks We've Talked About
- Overall Livability Score (metric) [High (simple calculation across multiple dimensions)] (need)
  - route: `GET /<city>/city_scr` (return a high-level score and then underlying sub-scores)

**Comment by AaronReichert** [comment]
FBI crime stats 1-5 stars overall plus the following categories.
Violent_crime
Murder_and_nonnegligent_manslaughter
Rape1
Robbery
Aggravated_assault
Property_crime
Burglary
Larceny_theft
Motor_vehicle_theft

**Comment by danoand** [comment]
Changed the documented routes above to be `/<route name>/<city>`.  The appropriate route name should precede the city path parameter

**Comment by danoand** [comment]
See the wiki for the high priority routes and response documents:
- https://github.com/Lambda-School-Labs/cityspire-d-ds/wiki/Sample-Routes

The DS API is now deployed to AWS.  View the automatic route documentation that comes with FastAPI here:
- https://cityspire-d-ds-01.eba-5qfhebrw.us-east-1.elasticbeanstalk.com/
