### ISSUE TITLE
Proposal: Use "Normalized" City Names when Calling FastAPI Routes

### ISSUE THREAD

**Issue by danoand** [Lambda-School-Labs/cityspire-d-ds#6]
_Making a change to this proposal that is consistent with how `walkscore.com` handles city names_

### BACKGROUND

- So far, all of the DS API routes take city name as a path parameter (e.g. `GET /city_scr/<city>`)
- Some city names include spaces and non-alpha characters (e.g. `St. Louis`, `Fort Wayne`)
- This may cause errors when invoking routes for those city variants

### PROPOSAL

- Propose we use some sort normalized or adjusted city name in these instances
- Normalized city names would have these adjustments:
   - convert spaces (" ") to underscores ("_")
   - remove all other characters that are not `alpha` or `underscores`

### Examples

- `Chicago` stays `Chicago` -> `GET /city_scr/Chicago `
- `St. Louis` becomes `St_Louis` -> `GET /city_scr/St_Louis `
- `New York` becomes `New_York` -> `GET /city_scr/New_York `

**Comment by schang1146** [comment]
I agree.

I like the system that you have set up for normalizing the city names.

Not sure what 3rd party APIs/DBs are doing for other special characters. I don't know if it'll be an issue for our case but cities can have other special characters. Not sure if we need to account for these.

(https://en.wikipedia.org/wiki/List_of_U.S._cities_with_diacritics)

**Comment by danoand** [comment]
Good point regarding other special characters.  We may not need that complexity for our particular use case but worth checking out.

Another option is to share a master list/mapping of cities in both the web and ds backends and have city names map to a code (e.g. `St. Louis` => `087`) and pass the code when calling the route

**Comment by danoand** [comment]
Closed on normalizing city names.  See the wiki for route documentation and examples: https://github.com/Lambda-School-Labs/cityspire-d-ds/wiki/Sample-Routes

Closing this issue
